python train_text_diffusion_t5.py \
  --dataset_name e2e \
  --adam_weight_decay 0.01 \
  --learning_rate 1e-4 \
  --num_train_steps 100000 \
  --train_batch_size 256 \
  --eval_batch_size 256 \
  --tx_dim 768 \
  --tx_depth 12 \
  --objective pred_x0 \
  --enc_dec_model ./assist_model/t5-base/ \
  --num_samples 1000 \
  --self_condition \
  --normalize_latent \
  --scale_shift \
  --loss_type l1 \
  --beta_schedule linear \
  --sampling_timesteps 2 \
  --save_and_sample_every 2 \
  --wandb_project denoising_diffusion \
  --wandb_name e2e-t5-linear

