export WANDB_MODE=offline
python train_text_diffusion.py \
  --learning_rate 0.0001 \
  --dataset_name ag_news \
  --num_train_steps 500000 \
  --train_batch_size 256 \
  --tx_dim 768 \
  --tx_depth 12 \
  --objective pred_x0 \
  --enc_dec_model ./assist_model/bart-base \
  --num_samples 1000 \
  --normalize_latent \
  --scale_shift \
  --disable_dropout \
  --beta_schedule linear \
  --loss_type l2 \
  --class_conditional \
  --self_condition \
  --save_and_sample_every 50000 \
  --wandb_project denoising_diffusion \
  --wandb_name ag-bart-l2